apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-www-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-www-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-www-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data2

